### ISSUE TITLE
cannot use with room

### ISSUE THREAD

**Issue by iceuncle** [amitshekhariitbhu/Android-Debug-Database#126]
cannot use with room

**Comment by amitshekhariitbhu** [comment]
Which version of room database?

**Comment by iceuncle** [comment]
1.0.0

**Comment by PoojaB26** [comment]
Yes, tried to test this with the Room's codelab sample. https://codelabs.developers.google.com/codelabs/android-persistence 
Throws a lot of compilation errors.

**Comment by PoojaB26** [comment]
I'm having these errors when I'm trying to include your li. Without it, app works. 

`
C:\Users\kiit1\Github\android-persistence-master\app\src\main\java\com\example\android\persistence\codelab\db\Loan.java:37: warning: book_id column references a foreign key but it is not part of an index. This may trigger full table scans whenever parent table is modified so you are highly advised to create an index that covers this column.
public class Loan {
       ^
C:\Users\kiit1\Github\android-persistence-master\app\src\main\java\com\example\android\persistence\codelab\db\Loan.java:37: warning: user_id column references a foreign key but it is not part of an index. This may trigger full table scans whenever parent table is modified so you are highly advised to create an index that covers this column.
public class Loan {
       ^
C:\Users\kiit1\Github\android-persistence-master\app\src\main\java\com\example\android\persistence\codelab\db\BookDao.java:45: warning: The query returns some columns [startTime, endTime, book_id, user_id, name, lastName, age] which are not use by com.example.android.persistence.codelab.db.Book. You can use @ColumnInfo annotation on the fields to specify the mapping.  You can suppress this warning by annotating the method with @SuppressWarnings(RoomWarnings.CURSOR_MISMATCH). Columns returned by the query: id, title, id, startTime, endTime, book_id, user_id, id, name, lastName, age. Fields in com.example.android.persistence.codelab.db.Book: id, title.
    LiveData<List<Book>> findBooksBorrowedByName(String userName);
                         ^
C:\Users\kiit1\Github\android-persistence-master\app\src\main\java\com\example\android\persistence\codelab\db\BookDao.java:53: warning: The query returns some columns [startTime, endTime, book_id, user_id, name, lastName, age] which are not use by com.example.android.persistence.codelab.db.Book. You can use @ColumnInfo annotation on the fields to specify the mapping.  You can suppress this warning by annotating the method with @SuppressWarnings(RoomWarnings.CURSOR_MISMATCH). Columns returned by the query: id, title, id, startTime, endTime, book_id, user_id, id, name, lastName, age. Fields in com.example.android.persistence.codelab.db.Book: id, title.
    LiveData<List<Book>> findBooksBorrowedByNameAfter(String userName, Date after);
                         ^
C:\Users\kiit1\Github\android-persistence-master\app\src\main\java\com\example\android\persistence\codelab\db\BookDao.java:60: warning: The query returns some columns [startTime, endTime, book_id, user_id, name, lastName, age] which are not use by com.example.android.persistence.codelab.db.Book. You can use @ColumnInfo annotation on the fields to specify the mapping.  You can suppress this warning by annotating the method with @SuppressWarnings(RoomWarnings.CURSOR_MISMATCH). Columns returned by the query: id, title, id, startTime, endTime, book_id, user_id, id, name, lastName, age. Fields in com.example.android.persistence.codelab.db.Book: id, title.
    List<Book> findBooksBorrowedByNameSync(String userName);
               ^
C:\Users\kiit1\Github\android-persistence-master\app\src\main\java\com\example\android\persistence\codelab\db\BookDao.java:66: warning: The query returns some columns [startTime, endTime, book_id, user_id] which are not use by com.example.android.persistence.codelab.db.Book. You can use @ColumnInfo annotation on the fields to specify the mapping.  You can suppress this warning by annotating the method with @SuppressWarnings(RoomWarnings.CURSOR_MISMATCH). Columns returned by the query: id, title, id, startTime, endTime, book_id, user_id. Fields in com.example.android.persistence.codelab.db.Book: id, title.
    LiveData<List<Book>> findBooksBorrowedByUser(String userId);
                         ^
C:\Users\kiit1\Github\android-persistence-master\app\src\main\java\com\example\android\persistence\codelab\db\BookDao.java:73: warning: The query returns some columns [startTime, endTime, book_id, user_id] which are not use by com.example.android.persistence.codelab.db.Book. You can use @ColumnInfo annotation on the fields to specify the mapping.  You can suppress this warning by annotating the method with @SuppressWarnings(RoomWarnings.CURSOR_MISMATCH). Columns returned by the query: id, title, id, startTime, endTime, book_id, user_id. Fields in com.example.android.persistence.codelab.db.Book: id, title.
    LiveData<List<Book>> findBooksBorrowedByUserAfter(String userId, Date after);
                         ^
C:\Users\kiit1\Github\android-persistence-master\app\src\main\java\com\example\android\persistence\codelab\db\BookDao.java:79: warning: The query returns some columns [startTime, endTime, book_id, user_id] which are not use by com.example.android.persistence.codelab.db.Book. You can use @ColumnInfo annotation on the fields to specify the mapping.  You can suppress this warning by annotating the method with @SuppressWarnings(RoomWarnings.CURSOR_MISMATCH). Columns returned by the query: id, title, id, startTime, endTime, book_id, user_id. Fields in com.example.android.persistence.codelab.db.Book: id, title.
    List<Book> findBooksBorrowedByUserSync(String userId);
               ^
C:\Users\kiit1\Github\android-persistence-master\app\build\generated\source\apt\debug\com\example\android\persistence\codelab\db\AppDatabase_Impl.java:22: error: AppDatabase_Impl is not abstract and does not override abstract method clearAllTables() in RoomDatabase
public class AppDatabase_Impl extends AppDatabase {
       ^`

**Comment by tangxiangpi** [comment]
me too, if i use room to create database , it not show on web browser

**Comment by bvisonl** [comment]
@tangxiangpi  Could this be the same case as of: #115 

Also, give a bit more info on your versions for room and android debug database... I have it working just fine now

**Comment by Xexiz** [comment]
Make sure you have the version 1.0.4 of the lib. Just tested and it's working well with latest fix in 1.0.4 on both device (API28) and emulator (API28)

I had several issues with 1.0.3 though.

`debugImplementation 'com.amitshekhar.android:debug-db:1.0.4'`
